### ISSUE TITLE
Archive type is blank

### ISSUE THREAD

**Issue by morojgovany** [buttercup/buttercup-browser-extension#175]
Hi ! 
I have a strange problem with the web extension, if I add a new archive on my personal webdav (nginx) conf :

```
location /dav {
        alias /path/dav;
        client_body_temp_path   /path/tmp;
        dav_methods             PUT DELETE MKCOL COPY MOVE;
        dav_ext_methods         PROPFIND OPTIONS;
        create_full_put_path    on;
        dav_access              user:rw group:rw;
        autoindex               on;
        auth_basic "restricted";
        auth_basic_user_file /path/passwd;
        proxy_connect_timeout  500s;
        proxy_read_timeout  500s;
        proxy_send_timeout  500s;
        send_timeout  500s;
     }
```

I have this error in the chrome console and the extension is freezing 

```
[info] Received full state update from background Objectapp: {busy: false, busyMessage: ""}busy: falsebusyMessage: "" 
[...] 
archives: 
archives: Array(1)0: 
colour: "#000000"
id: "9f2988ac-1f5f-4a67-8937-2f30bfd9cf9c"
name: "myDav"
order: 0state: "locked"
status: "locked"
title: "myDav"
type: ""                                                                           /* <= Strange behavior here*/
[...]
popup.js:1 Error: No image asset for archive type: 
    at popup.js:1
    at popup.js:1
    at Array.map (<anonymous>)
    at ArchivesListPage.value (popup.js:1)
    at ArchivesListPage.value (popup.js:1)
    at Lg (popup.js:1)
    at Sg (popup.js:1)
    at yh (popup.js:1)
    at zh (popup.js:1)
    at Wh (popup.js:1)
Yg @ popup.js:1
popup.html#/:1 Error in event handler for (unknown): Error: No image asset for archive type: 
    at chrome-extension://heflipieckodmcppbnembejjmabajjjj/popup.js:1:576628
    at chrome-extension://heflipieckodmcppbnembejjmabajjjj/popup.js:1:576763
    at ArchivesListPage.value (chrome-extension://heflipieckodmcppbnembejjmabajjjj/popup.js:1:576118)
    at ArchivesListPage.value (chrome-extension://heflipieckodmcppbnembejjmabajjjj/popup.js:1:575936)
    at Lg (chrome-extension://heflipieckodmcppbnembejjmabajjjj/popup.js:1:425788)
    at Sg (chrome-extension://heflipieckodmcppbnembejjmabajjjj/popup.js:1:430666)
    at yh (chrome-extension://heflipieckodmcppbnembejjmabajjjj/popup.js:1:440206)
    at zh (chrome-extension://heflipieckodmcppbnembejjmabajjjj/popup.js:1:440501)
    at Wh (chrome-extension://heflipieckodmcppbnembejjmabajjjj/popup.js:1:443995)
```

I think it's related to my new webdav because all is working fine with another one, but I can't figure out why so if you have any thought about the origin it would be very helpful for me !

screen:

![dav](https://user-images.githubusercontent.com/24272862/46352096-3ea21a00-c659-11e8-90a4-f240a67ef194.png)

Thank you !

**Comment by perry-mitchell** [comment]
This might be related to #173 - Did you notice any issue when _adding_ it to the extension? When exactly does it freeze?
