### ISSUE TITLE
Browser extension stopped working after auto-update to 3.0

### ISSUE THREAD

**Issue by spr2** [buttercup/buttercup-browser-extension#481]
- Browser application updated to 3.0
- Connecting to Desktop app 2.26.2 worked
- unlocking the first vault in the browser extension resulted in:

Unexpected Application Error!
Invalid URI format

URIError: Invalid URI format
    at ri.parse (chrome-extension://heflipieckodmcppbnembejjmabajjjj/scripts/popup.js:747:29350)
    at chrome-extension://heflipieckodmcppbnembejjmabajjjj/scripts/popup.js:832:1538
    at Dl (chrome-extension://heflipieckodmcppbnembejjmabajjjj/scripts/popup.js:653:240947)
    at t.unstable_runWithPriority (chrome-extension://heflipieckodmcppbnembejjmabajjjj/scripts/popup.js:653:303569)
    at Ga (chrome-extension://heflipieckodmcppbnembejjmabajjjj/scripts/popup.js:653:181800)
    at Pl (chrome-extension://heflipieckodmcppbnembejjmabajjjj/scripts/popup.js:653:240415)
    at chrome-extension://heflipieckodmcppbnembejjmabajjjj/scripts/popup.js:653:240326
    at D (chrome-extension://heflipieckodmcppbnembejjmabajjjj/scripts/popup.js:653:302629)
    at w.port1.onmessage (chrome-extension://heflipieckodmcppbnembejjmabajjjj/scripts/popup.js:653:301352)

Browser Extension stopped working completely!

![image](https://github.com/buttercup/buttercup-browser-extension/assets/9728327/ab22581c-5008-472e-8d51-10a383b4f5d1)

**Comment by perry-mitchell** [comment]
This has been fixed: #466
