### ISSUE TITLE
[Chrome] TypeError: Cannot read properties of undefined (reading 'length') when Site access is set to "On click"

### ISSUE THREAD

**Issue by Oxalin** [buttercup/buttercup-browser-extension#486]
Extension v3.1.0

Under Chrome, go under Menu > Add-ons and themes > Extensions > Buttercup > Manage
There, under "Site access", you will find "Allow this extension to read and change all your data on websites you visit:".
Set it to "On click"

For the Buttercup extension to be accessible, you will need to click on the icon in your Extension bar to let it read and change data so it can integrate itself next to username and password fields and be accessible.

Now, if you click on the extension icon to access its menu, it will fail and throw:
Unexpected Application Error!
Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
    at rn (chrome-extension://heflipieckodmcppbnembejjmabajjjj/scripts/popup.js:704:733)
    at io (chrome-extension://heflipieckodmcppbnembejjmabajjjj/scripts/popup.js:653:196095)
    at Bo (chrome-extension://heflipieckodmcppbnembejjmabajjjj/scripts/popup.js:653:205593)
    at $s (chrome-extension://heflipieckodmcppbnembejjmabajjjj/scripts/popup.js:653:248926)
    at Sl (chrome-extension://heflipieckodmcppbnembejjmabajjjj/scripts/popup.js:653:235300)
    at jl (chrome-extension://heflipieckodmcppbnembejjmabajjjj/scripts/popup.js:653:235228)
    at _l (chrome-extension://heflipieckodmcppbnembejjmabajjjj/scripts/popup.js:653:235091)
    at yl (chrome-extension://heflipieckodmcppbnembejjmabajjjj/scripts/popup.js:653:232088)
    at chrome-extension://heflipieckodmcppbnembejjmabajjjj/scripts/popup.js:653:182023
    at t.unstable_runWithPriority (chrome-extension://heflipieckodmcppbnembejjmabajjjj/scripts/popup.js:653:303569)

If you change the "Site access" option back to "On all sites", the extension will stop throwing error and it will work as intended.

This feature is not available under Firefox, so it is not reproducible.
Default config will prevent this error from happening (set to "On all sites").
It may affect other Chromium derivatives.

**Comment by Oxalin** [comment]
Full console log
![image](https://github.com/buttercup/buttercup-browser-extension/assets/303283/7bcdcfce-84bf-4b51-abff-d8ed6aca700f)

**Comment by perry-mitchell** [comment]
Didn't realise such a chrome feature existed. I'd be surprised if it's a large amount of users that have this enabled, but that's just a guess.

I wouldn't want supporting this to complicate the extension code too much. If it's a benign change then ok. Depends on what needs to be added to the following areas:

- Background tab handling
- Tab script 
- popup menu for current tab 

As of now this is an unsupported feature, until further notice.

**Comment by doublemarket** [comment]
This is not a request for the support but just a report to let you know there's another user who encountered the same issue. I spent some time to investigate the error until I came up with this GitHub issue as I've set "On click" enabled. Same with @Oxalin I enabled it to prevent unexpected behavior of the extension on some sites and to minimize security risks in general.

**Comment by perry-mitchell** [comment]
Happy to have someone contribute a PR for this, so long as it's as clean as possible and tested in every browser we support currently (chrome/edge/firefox).
